"""gender removed

Revision ID: 7cf3ccb0c518
Revises: d01d956d47c3
Create Date: 2025-09-29 23:46:43.178602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cf3ccb0c518'
down_revision: Union[str, None] = 'd01d956d47c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wallet_nonces_id', table_name='wallet_nonces')
    op.drop_index('ix_wallet_nonces_wallet_address', table_name='wallet_nonces')
    op.drop_table('wallet_nonces')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', postgresql.ENUM('male', 'female', name='gender'), autoincrement=False, nullable=False))
    op.create_table('wallet_nonces',
    sa.Column('wallet_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nonce', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wallet_nonces_pkey')
    )
    op.create_index('ix_wallet_nonces_wallet_address', 'wallet_nonces', ['wallet_address'], unique=True)
    op.create_index('ix_wallet_nonces_id', 'wallet_nonces', ['id'], unique=False)
    # ### end Alembic commands ###
